spring:
  application:
    name: "with-coroutine"
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:postgresql://localhost:5432/coroutine
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 50
      minimum-idle: 1
      transaction-isolation: TRANSACTION_READ_COMMITTED
      driver-class-name: org.postgresql.Driver